// react-app/src/App.js
import React, { useEffect, useRef } from "react";
import "./app.css";
import AppBuilderReactSdk from "@appbuilder/react";

function App() {
  const eventUnsubscriptionEvents = useRef([]);
  useEffect(() => {
    const myCustomization = AppBuilderReactSdk.createCustomization({
      // components:{
      //     videocall: () => <div>Hi</div>
      //   }
    });

    AppBuilderReactSdk.customize(myCustomization);

    const unsubCreateEvent = AppBuilderReactSdk.on(
      "create",
      (hostMeetingId, attendeeMeetingId, pstnNumber) => {
        console.log("React Host App: Meeting created with", {
          hostMeetingId,
          attendeeMeetingId,
          pstnNumber,
        });
      }
    );
    const unsubReadyToJoinEvent = AppBuilderReactSdk.on(
      "ready-to-join",
      (meetingTitle, deviceList) => {
        console.log("React Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }
    );
    const unsubJoinEvent = AppBuilderReactSdk.on(
      "join",
      (meetingTitle, deviceList, isHost) => {
        console.log("React Host App: joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }
    );
    const unsubLeaveEvent = AppBuilderReactSdk.on("leave", () => {
      console.log("React Host App: left");
    });

    eventUnsubscriptionEvents.current = [
      unsubCreateEvent,
      unsubReadyToJoinEvent,
      unsubJoinEvent,
      unsubLeaveEvent,
    ];

    return () => {
      unsubCreateEvent();
      unsubReadyToJoinEvent();
      unsubJoinEvent();
      unsubLeaveEvent();
    };
  }, []);

  const joinMeeting = () => {
    console.log(document.getElementById("meetingId").value);
    AppBuilderReactSdk.join(document.getElementById("meetingId").value);
  };

  const unsubscribe = () => {
    eventUnsubscriptionEvents.current.forEach((element) => {
      if (element) {
        console.log("elment", element);
        element();
      }
    });
  };

  return (
    <div className="App">
      <div className="header">
        <span>My React App</span>
        <input id="meetingId" type="text" placeholder="Room id"></input>
        <button onClick={joinMeeting}>Join</button>
        <button onClick={unsubscribe}>Unsubscribe</button>
      </div>
      <div style={{ display: "flex", flex: 1 }}>
        <AppBuilderReactSdk.View />
      </div>
    </div>
  );
}

export default App;

// angular-app/src/app/app.component.tsx
import React from "react";
import { Component } from "@angular/core";
import AppBuilderWebSdk from "@appbuilder/web";

// Prevent dead code elimination on react
React.createElement("div");

@Component({
  selector: "app-root",
  template: `
    <div class="App">
      <div class="header">
        <span>My Angular App</span>
        <input id="meetingId" type="text" placeholder="Room id" />
        <button (click)="JoinMeeting()">Join</button>
      </div>
      <div style=" display: flex; flex: 1 ">
        <app-builder> </app-builder>
      </div>
    </div>
  `,
  styleUrls: ["./app.component.css"],
})
export class AppComponent {
  title = "angular-app";

  unsubCreateEvent = () => {};
  unsubReadyToJoinEvent = () => {};
  unsubJoinEvent = () => {};
  unsubLeaveEvent = () => {};

  ngOnInit() {
    const myCustomization = AppBuilderWebSdk.createCustomization({
      // components:{
      //     videocall: () => <div>Hi</div>
      //   }
    });
    AppBuilderWebSdk.customize(myCustomization);

    this.unsubCreateEvent = AppBuilderWebSdk.on(
      "create",
      (hostMeetingId, attendeeMeetingId, pstnNumber) => {
        console.log("Angular Host App: Meeting created with", {
          hostMeetingId,
          attendeeMeetingId,
          pstnNumber,
        });
      }
    );
    this.unsubReadyToJoinEvent = AppBuilderWebSdk.on(
      "ready-to-join",
      (meetingTitle, deviceList) => {
        console.log("Angular Host App: precall with", {
          meetingTitle,
          deviceList,
        });
      }
    );
    this.unsubJoinEvent = AppBuilderWebSdk.on(
      "join",
      (meetingTitle, deviceList, isHost) => {
        console.log("Angular Host App: Meeting joined with", {
          meetingTitle,
          deviceList,
          isHost,
        });
      }
    );
    this.unsubLeaveEvent = AppBuilderWebSdk.on("leave", () => {
      console.log("Angular Host App: Meeting left");
    });
  }

  JoinMeeting() {
    AppBuilderWebSdk.join(
      (document.getElementById("meetingId") as HTMLInputElement).value!
    );
  }
  ngOnDestroy() {
    this.unsubCreateEvent();
    this.unsubReadyToJoinEvent();
    this.unsubJoinEvent();
    this.unsubLeaveEvent();
  }
}
